kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: assistant-db-pvc
  namespace: tia-hubble-prd-nat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: px-replicated
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi