apiVersion: v1
kind: Service
metadata:
  name: assistant-service
  namespace: tia-hubble-prd-nat
spec:
  selector:
    app: assistant-front
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP