[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = false


# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = true

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = true

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = false
    accept = ["*/*"]
    max_files = 2
    max_size_mb = 50

[features.audio]
    # Threshold for audio recording
    min_decibels = -45
    # Delay for the user to start speaking in MS
    initial_silence_timeout = 2000
    # Delay for the user to continue speaking in MS. If the user stops speaking for this duration, the recording will stop.
    silence_timeout = 700
    # Above this duration (MS), the recording will forcefully stop.
    max_duration = 15000
    # Duration of the audio chunks in MS
    chunk_duration = 1000
    # Sample rate of the audio
    sample_rate = 44100

# Allows user to use speech to text
[features.speech_to_text]
    enabled = false
    # See all languages here https://github.com/JamesBrill/react-speech-recognition/blob/HEAD/docs/API.md#language-string
    # language = "fr-FR"

[UI]
# Name of the assistant.
name = "Clara"

# Description of the assistant. This is used for HTML tags.
# description = ""

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
# custom_js = "/public/test.js"

# Specify a custom font url.
# custom_font = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"

# Specify a custom meta image url.
# custom_meta_image_url = "https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"


[UI.theme]
default = "dark"

# Override default MUI light theme.
[UI.theme.light]
background = "#F0F2F5"  # Soft, light gray for a gentle background.
paper = "#FFFFFF"       # Pure white for cards and surfaces.

[UI.theme.light.primary]
main = "#1E88E5"   # Vibrant blue for primary elements.
dark = "#1565C0"   # Darker blue for hover effects.
light = "#6AB7FF"  # Lighter blue for highlights.

[UI.theme.light.secondary]
main = "#FF4081"   # Pink accent color for secondary elements.

[UI.theme.light.text]
primary = "#212121"  # Dark gray for primary text.
secondary = "#757575"  # Medium gray for secondary text.

# Override default MUI dark theme.
[UI.theme.dark]
background = "#121212"  # Standard dark theme background.
paper = "#1E1E1E"       # Slightly lighter for card elements.

[UI.theme.dark.primary]
main = "#90CAF9"   # Light blue for contrast against dark background.
dark = "#5D99C6"   # Slightly darker blue for hover effects.
light = "#E3F2FD"  # Very light blue for highlights.

[UI.theme.dark.secondary]
main = "#F48FB1"   # Light pink accent color matching the light theme.

[UI.theme.dark.text]
primary = "#E0E0E0"  # Light gray for primary text.
secondary = "#B0B0B0"  # Medium-light gray for secondary text.

[meta]
generated_by = "1.2.0"
